[versions]
agp = "8.7.3"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
splashscreen = '1.0.1'
constraintlayout = "2.2.0"
lifecycleRuntimeKtx = "2.8.7"
lifecycleLivedataKtx = "2.8.7"
lifecycleViewmodelKtx = "2.8.7"
navigationFragment = "2.8.7"
navigationUi = "2.8.7"
cameraxVersion = "1.4.1"
roomVersion = "2.6.1"
coroutinesVersion = "1.7.3"
workVersion = "2.10.0"
permissionsDispatcher = "4.9.2"
hilt = "2.55"
kotlinx-metadata-jvm = "0.9.0"
pdfbox-android = '2.0.27.0'
pdf-viewer = "3.2.0-beta.1"
cardView = "1.0.0"
glide = "4.16.0"
ucrop = "2.2.10"
photoView = "2.0.0"
touchImageView = "3.6"
adMob = "23.6.0"
concurrent-futures = "1.2.0"
guava = "33.4.0-android"
serialization-json = "1.7.3"
lottie = "6.6.2"


[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
concurrent-futures = { group = "androidx.concurrent", name = "concurrent-futures", version.ref = "concurrent-futures" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
camerax-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraxVersion" }
camerax-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraxVersion" }
camerax-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraxVersion" }
camerax-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraxVersion" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomVersion" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomVersion" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomVersion" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutinesVersion" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutinesVersion" }
serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization-json" }
work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workVersion" }
permissions-dispatcher = { group = "com.github.permissions-dispatcher", name = "permissionsdispatcher", version.ref = "permissionsDispatcher" }
permissions-dispatcher-processor = { group = "com.github.permissions-dispatcher", name = "permissionsdispatcher-processor", version.ref = "permissionsDispatcher" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
kotlinx-metadata-jvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-metadata-jvm", version.ref = "kotlinx-metadata-jvm" }
pdfbox-android = { group = "com.tom-roush", name = "pdfbox-android", version.ref = "pdfbox-android" }
pdf-viewer = { group = "com.github.mhiew", name = "android-pdf-viewer", version.ref = "pdf-viewer" }
cardView = { group = "androidx.cardview", name = "cardview", version.ref = "cardView" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
ucrop = { group = "com.github.yalantis", name = "ucrop", version.ref = "ucrop"}
photoView = { group = "com.github.chrisbanes", name = "PhotoView", version.ref = "photoView" }
adMob = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "adMob" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
touchImageView = { group = "com.github.MikeOrtiz", name = "TouchImageView", version.ref = "touchImageView" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "1.9.0" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version = "2.1.0-1.0.29" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version = "2.1.0" }